In [1]:
import duckdb
import pandas as pd

In [2]:
con = duckdb.connect('../data/fpl-mentat.duckdb')

In [3]:
con.execute('select * from raw_log').fetchdf()

,id,payload,response_code,table_name,timestamp,status
0,1,"[{""code"": 3, ""draw"": 0, ""form"": null, ""id"": 1,...",200,events.raw_teams,2026-04-16 13:37:39.658762,success
1,2,"[{""can_transact"": true, ""can_select"": true, ""c...",200,events.raw_players,2026-04-16 13:37:39.689018,success
2,3,"[{""id"": 1, ""name"": ""Gameweek 1"", ""deadline_tim...",200,events.raw_events,2026-04-16 13:37:39.707964,success
3,4,"{""elements"": [{""id"": 1, ""stats"": {""minutes"": 9...",200,gw_data_gw1,2026-04-16 13:37:39.855714,success
4,5,"{""elements"": [{""id"": 1, ""stats"": {""minutes"": 9...",200,gw_data_gw2,2026-04-16 13:37:39.995289,success
...,...,...,...,...,...,...
316,317,"[{""code"": 2562232, ""event"": 34, ""finished"": fa...",200,fixtures_gw34,2026-04-20 16:39:46.426738,success
317,318,"[{""code"": 2562241, ""event"": 35, ""finished"": fa...",200,fixtures_gw35,2026-04-20 16:39:46.559869,success
318,319,"[{""code"": 2562249, ""event"": 36, ""finished"": fa...",200,fixtures_gw36,2026-04-20 16:39:46.704937,success
319,320,"[{""code"": 2562256, ""event"": 37, ""finished"": fa...",200,fixtures_gw37,2026-04-20 16:39:46.837902,success
320,321,"[{""code"": 2562265, ""event"": 38, ""finished"": fa...",200,fixtures_gw38,2026-04-20 16:39:46.969474,success

In [17]:
con.execute('select pg.player_id, pg.gameweek, pg.total_points, pg.minutes, p.first_name, p.second_name from stg_player_gameweek pg left join stg_players p on p.player_id = pg.player_id where gameweek = 33 and p.team_id = 13').fetchdf()

,player_id,gameweek,total_points,minutes,first_name,second_name
0,82.0,33,2.0,90.0,Antoine,Semenyo
1,182.0,33,0.0,0.0,James,Trafford
2,260.0,33,1.0,90.0,Marc,Guéhi
3,399.0,33,0.0,0.0,Ederson,Santana de Moraes
4,401.0,33,0.0,0.0,Marcus,Bettinelli
5,402.0,33,0.0,0.0,Rayan,Aït-Nouri
6,403.0,33,0.0,0.0,Joško,Gvardiol
7,404.0,33,0.0,0.0,Manuel,Akanji
8,405.0,33,1.0,1.0,Nathan,Aké
9,406.0,33,4.0,90.0,Abdukodir,Khusanov
10,407.0,33,5.0,90.0,Matheus,Nunes
11,408.0,33,0.0,0.0,Rúben,dos Santos Gato Alves Dias
12,409.0,33,0.0,0.0,John,Stones
13,410.0,33,0.0,0.0,Rico,Lewis
14,411.0,33,7.0,90.0,Nico,O'Reilly
15,412.0,33,0.0,0.0,Vitor,de Oliveira Nunes dos Reis
16,413.0,33,0.0,0.0,Omar,Marmoush
17,414.0,33,1.0,5.0,Phil,Foden
18,415.0,33,1.0,2.0,Sávio,Moreira de Oliveira
19,416.0,33,2.0,90.0,Bernardo,Mota Veiga de Carvalho e Silva
20,417.0,33,10.0,84.0,Rayan,Cherki
21,418.0,33,2.0,87.0,Jérémy,Doku
22,420.0,33,0.0,0.0,İlkay,Gündoğan
23,421.0,33,2.0,87.0,Rodrigo 'Rodri',Hernandez Cascante
24,422.0,33,0.0,0.0,Mateo,Kovačić
25,423.0,33,1.0,2.0,Nico,González Iglesias
26,425.0,33,0.0,0.0,Claudio,Echeverri
27,427.0,33,0.0,0.0,Tijjani,Reijnders
28,428.0,33,0.0,0.0,Sverre,Nypan
29,429.0,33,0.0,0.0,Kalvin,Phillips
30,430.0,33,6.0,90.0,Erling,Haaland
31,736.0,33,2.0,90.0,Gianluigi,Donnarumma
32,739.0,33,0.0,0.0,Divine,Mukasa
33,740.0,33,0.0,0.0,Stephen,Mfuni
34,742.0,33,0.0,0.0,Ryan,McAidoo
35,763.0,33,0.0,0.0,Charlie,Gray
36,764.0,33,0.0,0.0,Reigan,Heskey
37,794.0,33,0.0,0.0,Max,Alleyne

In [5]:
con.execute('select * from dim_teams').fetchdf()

    team_id       team_name
0         1         Arsenal
1         2     Aston Villa
2         3         Burnley
3         4     Bournemouth
4         5       Brentford
5         6        Brighton
6         7         Chelsea
7         8  Crystal Palace
8         9         Everton
9        10          Fulham
10       11           Leeds
11       12       Liverpool
12       13        Man City
13       14         Man Utd
14       15       Newcastle
15       16   Nott'm Forest
16       17      Sunderland
17       18           Spurs
18       19        West Ham
19       20          Wolves